# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """$all$shell$status$character"""
# format = """$username$time$shell"""

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold fg:#23d18b)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ](bold red)"
# Disable the package module, hiding it from the prompt completely

[shell]
fish_indicator = "ğŸŸ"
# powershell_indicator = ">_"
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false

[status]
style = "bg:blue"
symbol = "ğŸ”´"
success_symbol = "ğŸŸ¢"
sigint_symbol = "âœ‹"
format = '\[$symbol\] '
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = true

[package]
disabled = true
format = "via [ğŸ $version](208 bold) "

[time]
disabled = false
style = "fg:#8BE9FD"

[username]
disabled = false
show_always = true
# style = "red"
format = "[$user](bold fg:#ffb86c) in "

[directory]
truncation_length = 6
truncation_symbol = "â€¦/"
truncate_to_repo = false

[git_branch]
symbol = "ğŸŒ³ "

[git_state]
disabled = false

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ…"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "

[cmd_duration]
min_time = 1
format = "in [$duration](bold yellow)"

[env_var]
disabled = true
variable = "SHELL"
default = "unknown shell"

[line_break]
disabled = false

[localip]
ssh_only = true
format = "@[$localipv4](bold red) "
disabled = false

[hostname]
ssh_only = true
format = "[$ssh_symbol](bold fg:#8BE9FD) on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = "ğŸ "
style = "blue"
